retries: 4
delay: 5

retry_messages:
  - "&c<%item_name%> Hmmm... que feo nombre..."
success_messages:
  - "&a<%item_name%> Este si me gusta, esta genial!"
error_messages:
  - "&cUh-Oh! El item no pudo ser renombrado..."
already_renaming_messages:
  - "&cParece que ya estas renombrando un item!"
item_names:
  - "&b&nAutoClick"
  - "&c&nRaspberry"
  - "&8&nRompeanos"

retry_sounds:
  - "NOTE_PLING"
success_sounds:
  - "NOTE_PLING"
error_sounds:
  - "NOTE_PLING"