#############################################
# +=======================================+ #
#          BeaconReanme Created by          #
#      LinsaFTW afiliado a 2LS Studios      #
# +=======================================+ #
#############################################

# Esta opción permite ajustar la cantidad de mensajes enviados
# al jugador esta, estos mensajes se encuentran en "retry_messages:"
# Se recomienda dejarlo entre 4 o 5 para no recibir demasiado spam.
retries: 4

# Esta opcion permite ajustar los segundos en que se envia cada mensaje
# de la seccion "retry_messages:" la cantidad esta ajustada por ticks,
# los ticks funcionan de la siguiente manera (20 = 1 segundo).
delay: 10

# Mensajes de reintento. Puedes agregar los mensajes de intento que quieras,
# recuerda que si agregas muchos mensajes tienes que definir la cantidad de
# mensajes que apareceran en "retries:" 
retry_messages:
 - "%item_name% &e» &cHmmm... que feo nombre..."
 - "%item_name% &e» &cHmmm... no me convence..."
 - "%item_name% &e» &cHmmm... puede ser... mejor no."
 - "%item_name% &e» &cBueno pero puede haber mejores."
 
# Mensaje de renombrado exitoso. Puedes modificar este mensaje como gustes. 
success_messages:
 - "%item_name% &6» &aEste si me gusta, esta genial!"
 
# Mensaje de renombrado erroneo. Este mensaje aparece cuando no se renombro
# Un item por alguna razon, modificalo como gustes.
error_messages:
 - "&cUh-Oh! El item no pudo ser renombrado..."
 
# Seccion de Sonidos. En esta seccion estan los sonidos especificos de las 3
# secciones de mensajes de arriba. Todos lo sonidos los encuentras aqui.
# https://helpch.at/docs/1.8.8/index.html?org/bukkit/Sound.html
retry_sounds:
 - "NOTE_PLING"
 
success_sounds:
 - "LEVEL_UP"
 
error_sounds:
 - "VILLAGER_YES"
  
# Renombres añade los renombres que quieras con su respectivo color, estos
# se elegirán aleatoriamente.
item_names:
 - "&bAutoClick"
 - "&bL"
 - "&bDrip"
 - "&bVape"
 - "&bAnime"
 - "&bHuzuni"
 - "&bGang"
 - "&bExcalibur"
 - "&bSavage"
 - "&bBruh"
 - "&bUwU"
 - "6bDNS"
 - "&bEasy Money"
 - "&b$$$"
 - "&bRage"
 - "&bKiller"
 - "&bDAB"
 - "&bDemon"
 - "&bHacker"
 - "&bREKT"
 - "&bWEED"
 - "&bE-GIRL"
 - "&bGOD"
 - "&bQueen"
 - "&bEdater"
 - "&bRandy"
 - "&bLOL"
 - "&bpce"
 - "&bCrazy"
 - "&bTank"
 - "&bOG"
 - "&bMourning"
 - "&bMVP"
 - "&bBOO"
 - "&bGhoul"
 - "&bOP"
 - "&b</3"
 - "&bLove"
 - "&bGF"
 - "&bWARRIOR"
 - "&b⚠"
 - "&b<o/"
 - "&bClown"
 - "&bSimp"
 - "&bSauce"
 - "&byurrrrrrrr"
 - "&b.-."
 - "&b._."
 - "&bDeam Boy"
 - "&bBoy-Friend"
 - "&bDream"
 - "&b( ͡° ͜ʖ ͡°)"
 - "&b<3"
 - "&b#1"
  - "&bBad"
 - "&bBadBoy"
 - "&bHappy"
 - "&bPoggers"
 
