#############################################
# +=======================================+ #
#          BeaconReanme Created by          #
#                2LStudios                  #
# +=======================================+ #
#############################################

# Amount of retries before successfully renaming
retries: 4

# Delay between retries (in ticks)
delay: 10

# Permission to use BeaconRename
permission: "beaconrename.usage"

# Messages to show when retrying rename
retry_messages:
 - "%item_name% &e» &cHmmm... que feo nombre..."
 - "%item_name% &e» &cHmmm... no me convence..."
 - "%item_name% &e» &cHmmm... puede ser... mejor no."
 - "%item_name% &e» &cBueno pero puede haber mejores."
 
# Messages to show when rename was successful
success_messages:
 - "%item_name% &6» &aEste si me gusta, esta genial!"
 - "%item_name% &6» &aWoooW, este me encanta!"
 
# Messages to show when an error has ocurred
error_messages:
 - "&cUh-Oh! El item no pudo ser renombrado..."

# Messages to show when player doesn't have permission to use BeaconRename
no_permission_messages:
  - "&cParece que no tienes permisos para realizar eso..."
  - "&cNo tienes permisos suficientes!"
  - "&cYa veo parece que no tienes permisos."

# Available sounds (1.8): https://helpch.at/docs/1.8.8/index.html?org/bukkit/Sound.html
# Sounds to play when retrying rename
retry_sounds:
 - "LEVEL_UP"

# Sounds to play when rename was successful
success_sounds:
 - "ANVIL_USE"

# Sounds to play when an error has ocurred
error_sounds:
 - "VILLAGER_NO"

# Sound that plays when you do not have permissions
no_permission_sounds: 
 - "ITEM_BREAK"
 
# Randomly selected renames to apply with beacons
item_names:
 - "&bAutoClick"
 - "&bL"
 - "&bDrip"
 - "&bVape"
 - "&bAnime"
 - "&bHuzuni"
 - "&bGang"
 - "&bExcalibur"
 - "&bSavage"
 - "&bBruh"
 - "&bUwU"
 - "6bDNS"
 - "&bEasy Money"
 - "&b$$$"
 - "&bRage"
 - "&bKiller"
 - "&bDAB"
 - "&bDemon"
 - "&bHacker"
 - "&bREKT"
 - "&bWEED"
 - "&bE-GIRL"
 - "&bGOD"
 - "&bQueen"
 - "&bEdater"
 - "&bRandy"
 - "&bLOL"
 - "&bpce"
 - "&bCrazy"
 - "&bTank"
 - "&bOG"
 - "&bMourning"
 - "&bMVP"
 - "&bBOO"
 - "&bGhoul"
 - "&bOP"
 - "&b</3"
 - "&bLove"
 - "&bGF"
 - "&bWARRIOR"
 - "&b⚠"
 - "&b<o/"
 - "&bClown"
 - "&bSimp"
 - "&bSauce"
 - "&byurrrrrrrr"
 - "&b.-."
 - "&b._."
 - "&bDeam Boy"
 - "&bBoy-Friend"
 - "&bDream"
 - "&b( ͡° ͜ʖ ͡°)"
 - "&b<3"
 - "&b#1"
 - "&bBad"
 - "&bBadBoy"
 - "&bHappy"
 - "&bPoggers"
 - "&bPeces"
 - "&bDude"
 - "&bStonks"
 - "&bEasy"
 - "&bEz"
