#############################################
# +=======================================+ #
#          BeaconReanme Created by          #
#                2LStudios                  #
# +=======================================+ #
#############################################

# Amount of retries before successfully renaming
retries: 4

# Delay between retries (in ticks)
delay: 10

# Permission to use BeaconRename
permission: "beaconrename.usage"

# Messages to show when retrying rename
retry_messages:
 - "%item_name% &e» &cThat's not a good name..."
 - "%item_name% &e» &cHmmm... it doesn't convince me..."
 - "%item_name% &e» &cHmmm... maybe... or not..."
 - "%item_name% &e» &cOkay, but it could be better..."
 - "%item_name% &e» &cThat's not okay..."
 
# Messages to show when rename was successful
success_messages:
 - "%item_name% &6» &aI like this one, alright!"
 - "%item_name% &6» &aWooW! I love it!"
 - "%item_name% &6» &aThis is the one! Keep it!"
 
# Messages to show when an error has ocurred
error_messages:
 - "&cUh-Oh! The item can't be renamed..."
 - "&cAn error ocurred while renaming the item..."

# Messages to show when player doesn't have permission to use BeaconRename
no_permission_messages:
  - "&cIt seems you don't have permissions."
  - "&cYou don't have permissions to do this."
  - "&cI see, you have no permission to do this."

# Available sounds (1.8): https://helpch.at/docs/1.8.8/index.html?org/bukkit/Sound.html
# Sounds to play when retrying rename
retry_sounds:
 - "LEVEL_UP"

# Sounds to play when rename was successful
success_sounds:
 - "ANVIL_USE"

# Sounds to play when an error has ocurred
error_sounds:
 - "VILLAGER_NO"

# Sounds to play when you don't have permission to use BeaconRename
no_permission_sounds: 
 - "ITEM_BREAK"
 
# Randomly selected renames to apply with beacons
item_names:
 - "&bAutoClick"
 - "&bL"
 - "&bDrip"
 - "&bVape"
 - "&bAnime"
 - "&bHuzuni"
 - "&bGang"
 - "&bExcalibur"
 - "&bSavage"
 - "&bBruh"
 - "&bUwU"
 - "&bDNS"
 - "&bEasy Money"
 - "&b$$$"
 - "&bRage"
 - "&bKiller"
 - "&bDAB"
 - "&bDemon"
 - "&bHacker"
 - "&bREKT"
 - "&bWEED"
 - "&bE-GIRL"
 - "&bGOD"
 - "&bQueen"
 - "&bEdater"
 - "&bRandy"
 - "&bLOL"
 - "&bpce"
 - "&bCrazy"
 - "&bTank"
 - "&bOG"
 - "&bMourning"
 - "&bMVP"
 - "&bBOO"
 - "&bGhoul"
 - "&bOP"
 - "&b</3"
 - "&bLove"
 - "&bGF"
 - "&bWARRIOR"
 - "&b⚠"
 - "&b<o/"
 - "&bClown"
 - "&bSimp"
 - "&bSauce"
 - "&byurrrrrrrr"
 - "&b.-."
 - "&b._."
 - "&bDeam Boy"
 - "&bBoy-Friend"
 - "&bDream"
 - "&b( ͡° ͜ʖ ͡°)"
 - "&b<3"
 - "&b#1"
 - "&bBad"
 - "&bBadBoy"
 - "&bHappy"
 - "&bPoggers"
 - "&bPeces"
 - "&bDude"
 - "&bStonks"
 - "&bEasy"
 - "&bEz"
 - "&bBot"
 - "&b1Fps"
 - "&bPladins"
 - "&bEcho"
 - "&bAvenge"
 - "&bLinsaFTW"
 - "&bBest"
 - "&bMen"
 - "&bCorrupt"
 - "&bTo the Lobby"
 - "&bBack Later"
 - "&bFor the Gulag"
 - "&bEz Kite"
 - "&bBye Bye"
 - "&bWTF"
 - "&bHero"
 - "&bOvni"
 - "&bReptilian"
 - "&bUFO"
 - "&bGhost"
 - "&bXMouse"
 - "&b7Cliker"
 - "&bVelocity"
 - "&bMacros"
 - "&bDouble Click"
 - "&bOh Yeah"
 - "&bSoviet Tank"
 - "&bSee you Baby"
 - "&bSlayer"
 - "&bKill Aura"
 - "&bKill Aura TypeA"
 - "&bKill Aura TypeB"
 - "&bKill Aura TypeC"
 - "&bGood Job Boy"
 - "&bSlowest"
 - "&bFlameCord"
 - "&b2LS AntiBot"
 - "&bChatSentinel"
 - "&bExploitFixer"
 - "&bHamsterAPI"
 - "&6Goku"
 - "&6Trunks"
 - "&6Vegeta"
 - "&4DragonBall Z"
 - "&aBroly"
 - "&6SSJ3"
 - "&7Dragonborn"